server:
  port: 9004
spring:
  application:
    name: springboot-log
  datasource:
    url: jdbc:mysql://211.159.189.77:3306/seal_test?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      # 第一次简表create  后面用update
      ddl-auto: create
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

