server:
  port: 9200
spring:
  application:
    name: elasticserch
  data:
    elasticsearch:
      #测试单个172.18.21.222:9300成功
      cluster-nodes: 172.18.21.222:9300,172.18.21.223:9300
      cluster-name: my-application
      repositories:
        enabled: true
  rabbitmq:
    username: admin
    password: admin
    #addresses: 172.18.21.219:5672,172.18.21.220:5672,172.18.21.221:5672
    addresses: 134.175.12.243:5672
    listener:
      type: simple
      simple:
        concurrency: 5
        max-concurrency: 20
        acknowledge-mode: manual #设置手动确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms #尝试时间间隔
        default-requeue-rejected: false #重试失败后是否回队
    connection-timeout: 5000ms
    cache:
      channel:
        size: 5
    publisher-confirms: true #发布者消息确认
    publisher-returns: true  #发布者消息回调
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms #尝试时间间隔


    #spring:
    #  application:
    #    name: fcat-user
    #    port: 8950
    #  data:
    #    # Elasticsearch
    #    elasticsearch:
    #      #elasticsearch集群名称，默认的是elasticsearch
    #      cluster-name: my-application
    #      #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode,节点的地址 注意api模式下端口号是9300，千万不要写成9200
    #      cluster-nodes: 172.18.21.222:9300
    #      properties:
    #        path:
    #elasticsearch日志存储目录
    #logs: ./elasticsearch/log
    #elasticsearch数据存储目录
    #data: ./elasticsearch/data
  #是否开启本地存储
  #spring.data.elasticsearch.repositories.enable=true
  #        repositories:
  #          enable: true
