server:
  port: 9001
spring:
  ########配置上传文件大小#######
  servlet.multipart:
    max-file-size: 15MB
    max-request-size: 50MB
  application:
    name: springboot-easypoi
  datasource:
    url: jdbc:mysql://192.xxx.1.xxxx:xxxx/test?useUnicode=true&characterEncoding=UTF-8
    username: xxxx
    password: xxxx
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 1
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

######## mybatis-plus #########
mybatis-plus:
  mapper-locations: classpath*:/config/mapper/**/*.xml