server:
  port: 9700

spring:
  application:
    name: springboot-rabbitmq

  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.107.152.93:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      initial-size: 1
      max-active: 8
      min-idle: 1
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: "select x"
      filters: stat

  rabbitmq:
    username: admin
    password: admin@123
    addresses: 192.168.1.28:5672
    listener:
      type: simple
      simple:
        concurrency: 5
        max-concurrency: 20
        acknowledge-mode: manual #设置手动确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms #尝试时间间隔
        default-requeue-rejected: false #重试失败后是否回队
    connection-timeout: 5000ms
    cache:
      channel:
        size: 5
    publisher-confirms: true #发布者消息确认
    publisher-returns: true  #发布者消息回调
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms #尝试时间间隔
    virtual-host: /

  mail:
    from: fengzhiqiangzxx@163.com
    host: smtp.163.com
    password: fengzhiqiang
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: fengzhiqiangzxx@163.com

# 配置数据库
mybatis:
  mapper-locations: classpath:/mapper/*.xml

